### ISSUE TITLE
Card 컴포넌트 만들기

### ISSUE THREAD

**Issue by nyoung113** [prgrms-fe-devcourse/FEDC2_Shallenge_Jaeho#27]
Card 컴포넌트 생성
- user / challange / follow 에 쓰일 Card 컴포넌트를 만듭니다

**Comment by joSeugHee** [comment]
Container 컴포넌트가 어떤걸까요? Chakra-ui에서도 Container 컴포넌트가 있어서 혹시나 이름이 중복될것 같네요..!
