### ISSUE TITLE
Channel 컴포넌트 만들기

### ISSUE THREAD

**Issue by wogha95** [prgrms-fe-devcourse/FEDC2_Shallenge_Jaeho#62]
- Challenge 만드는 페이지에 들어갈 컴포넌트
   - chakra-ui Radio 사용
   - 8px씩 간격
   - 운동 / 독서 / 공부 / 루틴 / 자기계발

**Comment by joSeugHee** [comment]
채널 5개로 갯수가 정해져 있나요?
